### ISSUE TITLE
Change nav pills color to purple

### ISSUE THREAD

**Issue by citrusui** [2363web/bootstrap#20]
Better for branding purposes.

<img width="1166" alt="photo feb 22 6 44 23 am" src="https://cloud.githubusercontent.com/assets/9056756/13217448/69d5c820-d930-11e5-988d-1853d2971278.png">

**Comment by skyset** [comment]
I'm a little confused- what's the issue here?

**Comment by citrusui** [comment]
They're not purple, at least yet.
