### ISSUE TITLE
Too much text on homepage

### ISSUE THREAD

**Issue by skyset** [2363web/bootstrap#5]
"Research suggests that only 16% of people read web pages word-for-word. Most people scan. (source: Jakob Nielsen’s Alertbox)."

(http://lizwilson.me/simple-tips-to-improve-your-website-text/ READ THIS ARTICLE!!!)

Not sure whose idea it was to add a huge block of text to the homepage, but we need to seriously shorten it. I cannot stress enough how important it is to have concise, clear, and simple text on the website because otherwise it's just way too much and nobody is going to read it in the first place

**Comment by citrusui** [comment]
I'll look into this tonight. Most of the text was borrowed from http://team2363.org and has been updated only recently.

**Comment by skyset** [comment]
We had updated the text to be much shorter and more concise, but it seems
Andres added a ton of text to the fixed version. The article I mentioned in
the issue was mainly directed at him
