### ISSUE TITLE
Light footer

### ISSUE THREAD

**Issue by skyset** [2363web/bootstrap#6]
We need to change the layout of the footer, this is a given, but do you think we should change it to be dark and have the white icons like before?

**Comment by citrusui** [comment]
yeah sounds good :100:

**Comment by skyset** [comment]
👌

**Comment by citrusui** [comment]
ARL logo isn't going to look to good if we set the footer bg to dark.

**Comment by skyset** [comment]
We may need to just create a sponsors page like on the Materialize version

Samuel Tyler
Graphic Design and Web Development
Website: http://skyset.ga/
